### ISSUE TITLE
É possível exibir as respostas numa página html?

### ISSUE THREAD

**Issue by euisaquevenancio** [gazolla/GeminiChat#1]
é possível fazer com que este código exiba os resultados gerados pela IA através de "alerts", com JavaScript, ou no body de uma página "index.html"? Imagino que para isso seria necessário transformar esta classe em um Servlet.. pode me ajudar com isso?

**Comment by gazolla** [comment]
Acredito que a forma mais simples de fazer isso seria incluir esse código num projeto Spring/Springboot.

**Comment by isaquesv** [comment]
Entendi, muito obrigado pela dica!! bom projeto!!
